CREATE TABLE t_problems
(
    problem_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    title              VARCHAR(255),
    p_alias            VARCHAR(255),
    description        TEXT,
    input_description  TEXT,
    output_description TEXT,
    time_limit         INTEGER,
    memory_limit       INTEGER,
    judge_times        INTEGER,
    samples            JSONB,
    note               TEXT,
    author_user_id     BIGINT,
    CONSTRAINT pk_t_problems PRIMARY KEY (problem_id)
);

CREATE TABLE t_users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    password   VARCHAR(255),
    salt       VARCHAR(255),
    email      VARCHAR(255),
    real_name  VARCHAR(255),
    bio        VARCHAR(255),
    user_role  INTEGER,
    CONSTRAINT pk_t_users PRIMARY KEY (user_id)
);

CREATE TABLE t_announcements
(
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    title           VARCHAR(255),
    content         TEXT,
    author_user_id  BIGINT,
    visible         BOOLEAN,
    CONSTRAINT pk_t_announcements PRIMARY KEY (announcement_id)
);

ALTER TABLE t_problems
    ADD CONSTRAINT FK_T_PROBLEMS_ON_AUTHOR_USER FOREIGN KEY (author_user_id) REFERENCES t_users (user_id);

ALTER TABLE t_announcements
    ADD CONSTRAINT FK_T_ANNOUNCEMENTS_ON_AUTHOR_USER FOREIGN KEY (author_user_id) REFERENCES t_users (user_id);

CREATE TABLE t_files
(
    file_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    filename     VARCHAR(255),
    path         VARCHAR(255),
    hash         VARCHAR(255),
    url          TEXT,
    CONSTRAINT pk_t_files PRIMARY KEY (file_id)
);

ALTER TABLE t_problems
    ADD test_cases_file_id BIGINT;

ALTER TABLE t_problems
    ADD CONSTRAINT FK_T_PROBLEMS_ON_TESTCASES_FILE FOREIGN KEY (test_cases_file_id) REFERENCES t_files (file_id);

ALTER TABLE t_problems
    ADD background TEXT;

ALTER TABLE t_problems
    ADD visible BOOLEAN;
