CREATE TABLE t_judge_client_tokens
(
    token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    token      VARCHAR(255),
    enabled    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_judge_client_tokens PRIMARY KEY (token_id)
);
