CREATE TABLE t_contests
(
    contest_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    title            VARCHAR(255)                            NOT NULL,
    description      TEXT,
    start_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    freeze_time      INTEGER,
    type             VARCHAR(255)                            NOT NULL,
    permission       VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255),
    visible          BOOLEAN                                 NOT NULL,
    show_final_board BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_contests PRIMARY KEY (contest_id)
);

CREATE TABLE t_contests_problems
(
    problems_problem_id   BIGINT NOT NULL,
    t_contests_contest_id BIGINT NOT NULL
);

CREATE TABLE t_contests_users
(
    t_contests_contest_id BIGINT NOT NULL,
    users_user_id         BIGINT NOT NULL
);

ALTER TABLE t_contests_problems
    ADD CONSTRAINT fk_tconpro_on_contest FOREIGN KEY (t_contests_contest_id) REFERENCES t_contests (contest_id);

ALTER TABLE t_contests_problems
    ADD CONSTRAINT fk_tconpro_on_problem FOREIGN KEY (problems_problem_id) REFERENCES t_problems (problem_id);

ALTER TABLE t_contests_users
    ADD CONSTRAINT fk_tconuse_on_contest FOREIGN KEY (t_contests_contest_id) REFERENCES t_contests (contest_id);

ALTER TABLE t_contests_users
    ADD CONSTRAINT fk_tconuse_on_user FOREIGN KEY (users_user_id) REFERENCES t_users (user_id);
