CREATE TABLE t_self_test_submissions
(
    self_test_submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    user_user_id            BIGINT,
    language_language_id    BIGINT,
    code                    TEXT                                    NOT NULL,
    status                  VARCHAR(255),
    time_limit              INTEGER                                 NOT NULL,
    memory_limit            INTEGER                                 NOT NULL,
    time                    INTEGER,
    memory                  INTEGER,
    judge_stage             VARCHAR(255),
    compile_log             TEXT,
    input                   TEXT                                    NOT NULL,
    output                  TEXT,
    expected_output         TEXT,
    CONSTRAINT pk_t_self_test_submissions PRIMARY KEY (self_test_submission_id)
);

ALTER TABLE t_self_test_submissions
    ADD CONSTRAINT FK_T_SELF_TEST_SUBMISSIONS_ON_LANGUAGE_LANGUAGE FOREIGN KEY (language_language_id) REFERENCES t_languages (language_id);

ALTER TABLE t_self_test_submissions
    ADD CONSTRAINT FK_T_SELF_TEST_SUBMISSIONS_ON_USER_USER FOREIGN KEY (user_user_id) REFERENCES t_users (user_id);
