CREATE TABLE t_judger_system_status
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    judger_id    VARCHAR(255),
    os           VARCHAR(255),
    kernel       VARCHAR(255),
    memory_used  BIGINT,
    memory_total BIGINT,
    CONSTRAINT pk_t_judger_system_status PRIMARY KEY (id)
);

ALTER TABLE t_judger_system_status
    ADD CONSTRAINT uc_t_judger_system_status_judgerid UNIQUE (judger_id);

ALTER TABLE t_judge_client_tokens
    DROP COLUMN info_last_updated_at;

ALTER TABLE t_judge_client_tokens
    DROP COLUMN kernel;

ALTER TABLE t_judge_client_tokens
    DROP COLUMN memory_total;

ALTER TABLE t_judge_client_tokens
    DROP COLUMN memory_used;

ALTER TABLE t_judge_client_tokens
    DROP COLUMN os;
