CREATE TABLE t_submissions
(
    submission_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    user_user_id       BIGINT,
    problem_problem_id BIGINT,
    origin             INTEGER,
    language           VARCHAR(255),
    code               TEXT,
    status             VARCHAR(255),
    CONSTRAINT pk_t_submissions PRIMARY KEY (submission_id)
);

ALTER TABLE t_submissions
    ADD CONSTRAINT FK_T_SUBMISSIONS_ON_PROBLEM_PROBLEM FOREIGN KEY (problem_problem_id) REFERENCES t_problems (problem_id);

ALTER TABLE t_submissions
    ADD CONSTRAINT FK_T_SUBMISSIONS_ON_USER_USER FOREIGN KEY (user_user_id) REFERENCES t_users (user_id);
