CREATE TABLE t_languages
(
    language_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    language_name   VARCHAR(255),
    compile_command TEXT,
    execute_command TEXT,
    type            VARCHAR(255),
    enabled         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_languages PRIMARY KEY (language_id)
);
