CREATE TABLE t_articles
(
    article_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    title          VARCHAR(255),
    content        TEXT,
    author_user_id BIGINT,
    CONSTRAINT pk_t_articles PRIMARY KEY (article_id)
);

ALTER TABLE t_articles
    ADD CONSTRAINT FK_T_ARTICLES_ON_AUTHOR_USER FOREIGN KEY (author_user_id) REFERENCES t_users (user_id);
